blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/analytics-team/analytics-toolkit/discussions
    about: Ask questions, share ideas, and discuss the project with the community
  - name: 🔒 Security Issues
    url: https://github.com/analytics-team/analytics-toolkit/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📧 Direct Contact
    url: mailto:analytics-team@example.com
    about: Contact the maintainers directly for sensitive issues