name: Simple Pip Test

on:
  push:
    branches: [ feature/pytorch-statistical-regression ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies directly with pip
      run: |
        python -m pip install --upgrade pip
        pip install torch>=2.0.0 numpy>=1.24.0 pandas>=2.0.0 pytest>=7.0.0 scikit-learn>=1.3.0 matplotlib seaborn

    - name: Test basic imports
      run: |
        python -c "import torch; import pandas; import numpy; import sklearn; print('✅ All imports successful')"

    - name: Install package in development mode
      run: |
        pip install -e .

    - name: Test package import
      run: |
        python -c "import analytics_toolkit; print('✅ Package import successful')"

    - name: Run basic test
      run: |
        python -m pytest tests/test_utils.py -v